### PR TITLE
Add the debate id to the cache key for various template snippets

### PR DESCRIPTION
**Pull request by jbradberry**
so that when the question category is None (which happens when you are
not browsing under a particular category on the site), the item will
still be cached in a way that is debate-specific.

### CODE REVIEW

**Comment by nmashton** [comment]
How can I verify this?

**Comment by jbradberry** [comment]
@nmashton by having more than one Debate set up, creating Categories under both, and noting that the categories "bleed" into the other debate (or don't, in the case of this fix being applied).

Comment from the client describing this is here: https://docs.google.com/document/d/1gLjeJeN5NuTTv5nmlin7fTT6VZnA9jZQI9MNpY_kHEk/edit?disco=AAAABCOj-mA

**Comment by jbradberry** [comment]
Ditto questions.

**Comment by nmashton** [comment]
I'm not able to reproduce the issue locally on `develop`, which makes it hard to confirm that this has fixed it. I'm at a loss. Adding a new parameter to the cache tag doesn't _hurt_ anything significantly, though, so if you want to merge it … I see no real reason not to. 🚢 ?

**Pull request merged**
