### PR TITLE
Get SECRET_KEY from the environment

### PR DESCRIPTION
**Pull request by vkurup**
Needs https://github.com/caktus/fabulaws/pull/11 to work properly during deployment.

### CODE REVIEW

**Comment by vkurup** [comment]
I'll also need to add a SECRET_KEY to fabsecrets.py and then run `fab testing update_server_passwords`, and then try a deploy.

**Comment by dpoirier** [comment]
This looks fine once the Fabulaws changes are merged and this is all tested.

**Comment by dpoirier** [comment]
I think I agree with @tobiasmcnulty about doing this consistently with the other secrets.

**Comment by dpoirier** [comment]
:shipit:

**Pull request merged**
