### PR TITLE
Let people still see removed submissions, but without any actions

### PR DESCRIPTION
**Pull request by ejucovy**

### CODE REVIEW

**Comment by jbradberry** [comment]
As in, go to the detail page for a question even if it has been removed via moderation?

**Comment by ejucovy** [comment]
Exactly - sorry.  Per https://basecamp.com/1849796/projects/11504603/messages/62449457#comment_461794670 the proposed change would:
- Continue to make removed questions invisible in all list views / searches / etc, so they can't be navigated to from within the site
- Continue to disallow votes, shares, and flags of removed questions
- But allow direct links to still work - so if someone shares their idea on facebook, and it's then removed via moderation, the page would show the idea with a "This question has been removed by moderators" notice instead of a bare 404.

**Comment by jbradberry** [comment]
Sounds like a decent idea.

**Comment by jbradberry** [comment]
@ejucovy reviewing now, unless you intend to do more...

**Comment by jbradberry** [comment]
This looks good to me.  :+1:

**Pull request merged**
