### PR TITLE
Make sure "headline" field is indexed for search

### PR DESCRIPTION
**Pull request by ejucovy**
I'm pretty sure this change is needed to make headlines participate in search results at all.  I'll try to add a test to this PR soon - and also check whether changes are needed in the "merge ideas" logic to support headlines too.  But wanted to get this to you as soon as I noticed it.

### CODE REVIEW

**Comment by dpoirier** [comment]
It looks like we should also add a 'text search' index to the `search_index` field?  (https://github.com/linuxlewis/djorm-ext-pgfulltext/blob/f9aaf6079dc6296708c794c7ee994482de56c746/djorm_pgfulltext/models.py#L70)

**Comment by ironfroggy** [comment]
And with our infrastructure, do we have an established way to run the update command for this change to be indexed?

**Comment by dpoirier** [comment]
What update command do we need to run? I thought since this was a postgres search, and we have `auto_update_search_field=True` on the SearchManager, that would keep things updated as we went along?

But if we do need to run an update command, it'll be easy to add as another Celery periodic task.

**Comment by ejucovy** [comment]
Sorry, I didn't realize these comments were directed towards me (thought they were internal).  But hmm, yeah - I think you're right.  Here's my interpretation of the docs.  Let me know if this sounds correct to you -- I don't really know anything about postgres search beyond having found last year that this django plugin magically worked and I wouldn't need to learn solr after all. :)

* We should add a text index to the search_index field to improve search performance.  Looks like that would mean running a one-time psql command like `CREATE INDEX opendebates_submission_search_idx ON opendebates_submission USING gin(to_tsvector('english', search_index));`
* The django plugin code will handle merging the values of the various fields named in the `SearchManager(fields=[])` array and stuffing them in the `search_index` field, every time a model changes.  So we shouldn't need to update the index in an ongoing way.
* But if we push code to a live installation that changes the list of fields participating in search after the database has been populated, we should run `manage.py update_search_field opendebates` as part of the deployment in order to regenerate the values in the `search_index` column for existing rows.  https://github.com/linuxlewis/djorm-ext-pgfulltext#update-search-field

**Comment by ejucovy** [comment]
While I'm looking at these docs - do we also need to "install the extension unaccent" when creating the database?  https://github.com/linuxlewis/djorm-ext-pgfulltext#general-notes

**Comment by dpoirier** [comment]
Tried that create index:

    psql (9.4.5)
    Type "help" for help.

    opendebates=# CREATE INDEX opendebates_submission_search_idx ON opendebates_submission USING gin(to_tsvector('english', search_index));
    ERROR:  function to_tsvector(unknown, tsvector) does not exist
    LINE 1: ...on_search_idx ON opendebates_submission USING gin(to_tsvecto...
                                                                 ^
    HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

**Comment by ejucovy** [comment]
Drat.  Well strictly speaking I think that create index is "only" important for performance, so maybe we can track that in a separate issue later to figure out what's missing.  In terms of this PR, I think the only things that are strictly necessary are the code update I posted so that new submissions get their headlines included in the search_index database field + possibly running the manage.py update_search_field command as a one time "migration" for existing data.

**Pull request merged**
