### PR TITLE
Cleaning up header spacing and fonts, per requests

### PR DESCRIPTION
**Pull request by ironfroggy**

### CODE REVIEW

**Comment by ejucovy** [comment]
This looks amazing on wide screens, and looks like it addresses all the concerns we had, thanks.  The mobile version also looks correct.  I did some testing on different sizes in between and saw a few different responsive glitches along the way -- not sure if you were planning on tackling those separate from the main versions but wanted to flag in case it's helpful.

Between 1192 and 1001 px screen width, the content disappears:

screen shot 2016-03-30 at 8 46 18 am

Between 1000 and 803 px screen width, it reappears, but misaligned vertically and running below the height of the banner; and meanwhile the partner logos crowd up against each other unappealingly:

screen shot 2016-03-30 at 8 47 57 am

Between 802 and 801 px screen width it disappears again:

screen shot 2016-03-30 at 8 49 03 am

At exactly 800 px screen width, the partner logos disappear too, and the brand logo loses its left margin:

screen shot 2016-03-30 at 8 50 09 am

And then at 799 px width and below we get the mobile header version, which looks correct to me.

**Comment by ironfroggy** [comment]
@ejucovy thanks for putting this through its pacing and finding those cases. I'll take a pass between the mobile and desktop layouts to get all these sorted out.

**Comment by dpoirier** [comment]
I also noticed these as I narrowed my browser:

* Around 765 px, the layout changes and everything is visible again, but the
sponsor logos (PGI & CNN) have been scaled way up and look grainy and
out of proportion to the rest.
* At 259, the LOGIN/REGISTER text is bumping into the logo.

**Comment by dpoirier** [comment]
2016-03-30-133342_3280x1080_scrot
Around 676 px, the two sponsor images (PGI & CNN) fall out of alignment with each other.

**Comment by dpoirier** [comment]
At a width of 1127, a lot of the content still vanishes.

2016-03-30-133637_3280x1080_scrot

**Comment by ejucovy** [comment]
On all widths greater than the mobile breakpoint, the vertical alignment of the partner logos vs the vote counter is slightly off now -- it looks like the partner logos are 10-12px higher than they ought to be:

screen shot 2016-03-30 at 2 20 25 pm

**Comment by dpoirier** [comment]
Still seeing the issue from this comment https://github.com/caktus/django-opendebates/pull/104#issuecomment-203544535

**Comment by dpoirier** [comment]
I think the vanishing content problem is fixed (knock on wood!).

I'm seeing another issue now. There are some widths a little above the mobile responsive break point where the end of the paragraph of text is hidden behind the total votes counter.

2016-03-31-120336_3280x1080_scrot

**Comment by dpoirier** [comment]
:+1:

**Pull request merged**
