### PR TITLE
[OP-109] Mobile Modal style fixes

### PR DESCRIPTION
**Pull request by ironfroggy**

### CODE REVIEW

**Comment by dpoirier** [comment]
When I put my browser in fake mobile mode (400 x 690) and clicked Login, it looked as if nothing had happened and I started wondering what was broken. It wasn't until I happened to scroll down that I saw that the login modal had appeared below all the header content and wasn't even visible until I scrolled down. I think it ought to pop up over the header content, near or at the top of my mobile screen, maybe even fixed to the top of the screen.

**Comment by dpoirier** [comment]
Not a modal, but testing on this branch still in mobile mode, it looks like the breadcrumbs wrap around on top of the question display:

2016-03-30-134521_3280x1080_scrot

Also, I would expect the bread crumb to have the question headline, not the question body.

**Comment by ejucovy** [comment]
Hm -- maybe we should actually just hide the last element of the breadcrumb
bar on mobile altogether, since it's just duplicating what's on the next
line anyway.

In terms of the mobile header content, we may end up proposing to eliminate
most of that -- it's not just a problem for login; all pages on mobile are
pushed down unreasonably far by the super long content.  We'll circle back
to this one after a bit more discussion on our end.

**Comment by ejucovy** [comment]
BTW, I finally just managed to test this on an actual Android phone and it's looking great to me.  I'd vote for merging this, and then I can work on addressing dpoirier's comments separately in another batch-of-style-tweaks PR.

**Comment by dpoirier** [comment]
It sounds like the remaining "issues" are a design decision for @ejucovy et al, so I'll go ahead and merge this so we can move forward.

**Pull request merged**
